# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.30
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21862794584
# Commit: https://github.com/zenopie/earth-network-backend/commit/84af9b5cb29feff987248eaddbee14a5263709c1
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:768e967403bdff07e1e7703c46304053814439a8883b80ba60dd08a70c51c98f
    ports:
      - '8000'
