# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.20
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/20840769104
# Commit: https://github.com/zenopie/earth-network-backend/commit/dee8a28c51aa5f6a8a77bd743f9bb955bfd0ef14
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:e287669ee272199c7f6799ca5c3c75c9d0e0c0b8a0d987f157e7a55b1820917d
    ports:
      - '8000'
