# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.31
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21863380601
# Commit: https://github.com/zenopie/earth-network-backend/commit/0b88dc2252272b4481acdd4dbedcca7376e9e4d4
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:da8ddd53efcd38f20dfa2f434c777dec162d7013e95c3c8bd78d4ec4c0cf7f6e
    ports:
      - '8000'
