# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.25
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21809005772
# Commit: https://github.com/zenopie/earth-network-backend/commit/f05031e8bf2e0701fec655102b969c045e7efc93
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:4cfcdc6cd5167a2c0db327600f86f363084a7e67495e7b0a659ca7d5759976d3
    ports:
      - '8000'
