# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.28
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21862357336
# Commit: https://github.com/zenopie/earth-network-backend/commit/02d2437b6d922021cb7dffb939c31c5ca106ee0d
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:c3a316f735cdfeb17a71858894297c222b058ce8fb0d4dc30cccf4129147400b
    ports:
      - '8000'
