# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.32
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21863693828
# Commit: https://github.com/zenopie/earth-network-backend/commit/8f0a61d0c484200bb09999d27781e6e08942a0ca
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:62ffe65046c058ad76b91d2313f61719a1e675fda4745e52f0d3801e19b53a08
    ports:
      - '8000'
