# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.22
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21573557723
# Commit: https://github.com/zenopie/earth-network-backend/commit/adcd2f57117e9018ea404070500f2db34e231b17
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:6025c5d0a36b61cc9b23ea65414ece53fe6a1116bbad1e213504af074f6c961e
    ports:
      - '8000'
