# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.26
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21854897456
# Commit: https://github.com/zenopie/earth-network-backend/commit/89191fe7eaa64e0b101ab349ede4a4106a814ad6
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:a9772d8089d89e3767a0c0c36397b1e2f516b9acf9a01298f582b7dbe86371c2
    ports:
      - '8000'
