# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.16
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/19200592516
# Commit: https://github.com/zenopie/earth-network-backend/commit/c1a8b9e36ad0b3b5d236dee65bdb036986cceb2f
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:e54c2ff7886a65efd602f0ad526c155004fcd109a4aa8fb493908aa68fb87f7d
    ports:
      - '8000'
