# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.33
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/22298225987
# Commit: https://github.com/zenopie/earth-network-backend/commit/ab2cbb12808b0377e0cd52a24d03afd1c3e93c87
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:d9ba01c0e2e6b6e5c6c6e15123a26f9f192721743a354e30937df2fa8391df14
    ports:
      - '8000'
