# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.27
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21855065548
# Commit: https://github.com/zenopie/earth-network-backend/commit/1165790cb705e0ae2548dfa2d3ab6c7b609f7727
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:9f04cb136edcf65044d05afe575c455fa39105a6ea240ad78372c9ba3924c40b
    ports:
      - '8000'
