# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.23
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21573757964
# Commit: https://github.com/zenopie/earth-network-backend/commit/7b42f9d6a75f9560669ae57d0619b43c18bb0c80
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:c90d087c6bbad76a03788a2463a4452bcfde7436a21edddd6facb5b960a2e794
    ports:
      - '8000'
