# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.17
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/19238942659
# Commit: https://github.com/zenopie/earth-network-backend/commit/8375b3743d74b76de1e826c72177fc593de842c7
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:6bf5a2ea2a0b8146a0692f39b0f8f3b86c73127e9ae014e7582a7c5307f39e6c
    ports:
      - '8000'
