# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.15
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/19153194979
# Commit: https://github.com/zenopie/earth-network-backend/commit/d5efa24233ab85255b8dc5617c14e6e830db309f
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:8d48c2c7cf7278a34d6c86e5d6b43db4903f0fea2749fdddf70e072fda3e4e14
    ports:
      - '8000'
