# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.29
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21862590667
# Commit: https://github.com/zenopie/earth-network-backend/commit/f8c4484010f07401a5a1947a2b3ef419b9b88f04
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:673a68435bd3cd3a1f43007a1541fd5ce212cd4f3e8c8aa39ace4ec3c55dd040
    ports:
      - '8000'
