# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.18
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/19241814580
# Commit: https://github.com/zenopie/earth-network-backend/commit/bfe0056e7ef50549433bff01038af308165ce137
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:07780b73d617a6c149834739c0522b20c3848731d51fdd6aef136bd56ba47a4d
    ports:
      - '8000'
