# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.21
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/21413022946
# Commit: https://github.com/zenopie/earth-network-backend/commit/d9958443b8a8332f9d22f668a62014ea2560f418
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:9ab37856aec614b4bf9c54e12f2ff62061eb47cdc25e198d7d954babba611349
    ports:
      - '8000'
