# Release: https://github.com/zenopie/earth-network-backend/releases/tag/v1.1.19
# Workflow URL: https://github.com/zenopie/earth-network-backend/actions/runs/19340843186
# Commit: https://github.com/zenopie/earth-network-backend/commit/b5621c7644102268c08fd31db786c4f218f74f0e
# Dockerfile Path: Dockerfile
# Docker Compose Location: ./docker-compose-secretvm.yaml
version: '3'
services:
  app:
    image: ghcr.io/zenopie/earth-network-backend@sha256:9966ca6be59a474562d0fb75371fdd1b78bafaf8126fe516b76d449841cfdba3
    ports:
      - '8000'
